### PR TITLE
Solved issue #18

### PR DESCRIPTION
**Pull request by suryatejreddy**
The images are stored in a new folder called feedback

### CODE REVIEW

**Comment by naman** [comment]
Umm, your commit shows that you are storing it in the DB. Are you sure you are creating a folder?

**Comment by suryatejreddy** [comment]
Ohh sorry. I though upload_to creates a new folder named as feedback,  and stores the uploaded images there.

**Comment by naman** [comment]
@suryatejreddy any progress on this?

**Comment by suryatejreddy** [comment]
I do not seem to understand what to change, because in the docs, its given that upload_to='folder_name' will upload it to a folder.

**Comment by naman** [comment]
meet me :P

**Pull request merged**
